version: "3.1"
services:

  mysqldb:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - internetshop-mysqldb
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=internetshopdb
       - MYSQL_USER=ros
       - MYSQL_PASSWORD=Qwerty12

  mongodb:
    image: mongo:latest
    container_name: mongodb1
    networks:
      - internetshop-mongodb


  internetshop:
    image: internetshop
    container_name: internetshop
    ports:
      - 8080:8080
    networks:
      - internetshop-mysqldb
      - internetshop-mongodb
    depends_on:
      - mysqldb
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/internetshopdb

networks:
  internetshop-mysqldb:
    driver: bridge
  internetshop-mongodb:
    driver: bridge
